server:
  port: 8012

spring:
  application:
    name: spring-cloud-config-client

#eureka:
#  client:
#    # 实例是否在eureka服务器上注册自己的信息以提供其他服务发现,默认为true
#    register-with-eureka: true
#    # 此客户端是否获取eureka服务器注册表上的注册信息,默认为true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka