server:
  port: 8002

spring:
  application:
    name: server-provider

eureka:
  instance:
    # eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    # eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒。
    registry-fetch-interval-seconds: 10
    # 注册地址
    serviceUrl:
      defaultZone: http://localhost:8000/eureka