server:
  port: 8088

spring:
  application:
    name: mq-provider1
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: root
      password: root

eureka:
  instance:
    lease-expiration-duration-in-seconds: 10  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 5      #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: true       # 表示是否将自己注册到Eureka Server，默认为true。
    fetch-registry: true             # 表示是否从Eureka Server获取注册信息，默认为true。
    serviceUrl:
      defaultZone: http://wangyisongku:wangyisongku@localhost:8000/eureka

feign:
  hystrix:
    enabled: true