server:
  port: 8000

spring:
  application:
    name: eureka-server
  security:
    user:
      name: wangyisongku
      password: wangyisongku

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true   #显示ip信息
  client:
    # 实例是否在eureka服务器上注册自己的信息以提供其他服务发现,默认为true
    register-with-eureka: false
    # 此客户端是否获取eureka服务器注册表上的注册信息,默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理无效节点（单位毫秒，默认是60*1000，即60秒）
    eviction-interval-timer-in-ms: 4000

